CREATE USER bere1 WITH ENCRYPTED PASSWORD 'Ciucas';
GRANT ALL PRIVILEGES ON DATABASE Bb4kMerch TO bere1;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bere1;
GRANT ALL PRIVILEGES ON ALL  SEQUENCES IN SCHEMA public TO bere1;
